name: conexion
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  dropdown_button2: ^1.9.2
  http: ^0.13.5
  flutter_svg: ^1.1.6
  flutter_swiper: ^1.1.6
  url_launcher: ^6.1.9
  percent_indicator: ^4.2.2

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

